name = "rail-announcements"
compatibility_date = "2026-02-24"
pages_build_output_dir = "out"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "rail-announcements"
database_id = "49f5fff6-f5dd-475c-b5ae-b1d617fd8fc2"
