// Generated from a KeTech PCC announcement card read out of a 1973 Tube Stock digital voice
// announcer, cross-referenced against the Piccadilly Line Night Tube DVA functional definition
// specification (KeTech, NTS-PT00694-SY-3001 issue 01) for the spoken text of each audio ID.
//
// `text` is what the announcement says; `screenText` is the string the card holds for the
// passenger information display, which is often an abridged form and is absent entirely for
// announcements that leave the display unchanged.

export interface IPiccadillyClip {
  /** Audio file ID as numbered in the functional definition specification. */
  specId: number
  clip: string
  text: string
  screenText: string | null
  /** Length of the recording in seconds, used to step the display through an announcement. */
  duration: number
}

export interface IPiccadillyStation {
  /** Station number as numbered in the functional definition specification. */
  number: number
  name: string
  atStation: IPiccadillyClip | null
  approaching: IPiccadillyClip | null
  destination: IPiccadillyClip | null
}

export const Stations: IPiccadillyStation[] = [
  {
    number: 1,
    name: 'Cockfosters',
    atStation: {
      specId: 101,
      clip: 'this station.cockfosters',
      text: 'This is Cockfosters',
      screenText: 'This is Cockfosters',
      duration: 1.952,
    },
    approaching: {
      specId: 201,
      clip: 'next station.cockfosters',
      text: 'The next station is Cockfosters.',
      screenText: 'The next station is Cockfosters',
      duration: 2.752,
    },
    destination: {
      specId: 701,
      clip: 'destination.cockfosters',
      text: 'This is a Piccadilly Line service to Cockfosters.',
      screenText: 'Piccadilly Line to Cockfosters',
      duration: 3.872,
    },
  },
  {
    number: 3,
    name: 'Oakwood',
    atStation: {
      specId: 103,
      clip: 'this station.oakwood',
      text: 'This is Oakwood.',
      screenText: 'This is Oakwood',
      duration: 1.568,
    },
    approaching: {
      specId: 203,
      clip: 'next station.oakwood',
      text: 'The next station is Oakwood.',
      screenText: 'The next station is Oakwood',
      duration: 2.368,
    },
    destination: {
      specId: 703,
      clip: 'destination.oakwood',
      text: 'This is a Piccadilly Line service to Oakwood.',
      screenText: 'Piccadilly Line to Oakwood',
      duration: 3.488,
    },
  },
  {
    number: 4,
    name: 'Southgate',
    atStation: {
      specId: 104,
      clip: 'this station.southgate',
      text: 'This is Southgate.',
      screenText: 'This is Southgate',
      duration: 1.76,
    },
    approaching: {
      specId: 204,
      clip: 'next station.southgate',
      text: 'The next station is Southgate.',
      screenText: 'The next station is Southgate',
      duration: 2.56,
    },
    destination: {
      specId: 704,
      clip: 'destination.southgate',
      text: 'This is a Piccadilly Line service to Southgate.',
      screenText: 'Piccadilly Line to Southgate',
      duration: 3.68,
    },
  },
  {
    number: 5,
    name: 'Arnos Grove',
    atStation: {
      specId: 105,
      clip: 'this station.arnos grove',
      text: 'This is Arnos Grove.',
      screenText: 'This is Arnos Grove',
      duration: 1.856,
    },
    approaching: {
      specId: 205,
      clip: 'next station.arnos grove',
      text: 'The next station is Arnos Grove.',
      screenText: 'The next station is Arnos Grove',
      duration: 2.656,
    },
    destination: {
      specId: 705,
      clip: 'destination.arnos grove',
      text: 'This is a Piccadilly Line service to Arnos Grove.',
      screenText: 'Piccadilly Line to Arnos Grove',
      duration: 3.776,
    },
  },
  {
    number: 7,
    name: 'Bounds Green',
    atStation: {
      specId: 107,
      clip: 'this station.bounds green',
      text: 'This is Bounds Green.',
      screenText: 'This is Bounds Green',
      duration: 1.856,
    },
    approaching: {
      specId: 207,
      clip: 'next station.bounds green',
      text: 'The next station is Bounds Green.',
      screenText: 'The next station is Bounds Green',
      duration: 2.656,
    },
    destination: {
      specId: 707,
      clip: 'destination.bounds green',
      text: 'This is a Piccadilly Line service to Bounds Green.',
      screenText: 'Piccadilly Line to Bounds Green',
      duration: 3.776,
    },
  },
  {
    number: 8,
    name: 'Wood Green',
    atStation: {
      specId: 108,
      clip: 'this station.wood green',
      text: 'This is Wood Green.',
      screenText: 'This is Wood Green',
      duration: 1.728,
    },
    approaching: {
      specId: 208,
      clip: 'next station.wood green',
      text: 'The next station is Wood Green.',
      screenText: 'The next station is Wood Green',
      duration: 2.528,
    },
    destination: {
      specId: 708,
      clip: 'destination.wood green',
      text: 'This is a Piccadilly Line service to Wood Green.',
      screenText: 'Piccadilly Line to Wood Green',
      duration: 3.648,
    },
  },
  {
    number: 9,
    name: 'Turnpike Lane',
    atStation: {
      specId: 109,
      clip: 'this station.turnpike lane',
      text: 'This is Turnpike Lane.',
      screenText: 'This is Turnpike Lane',
      duration: 2.016,
    },
    approaching: {
      specId: 209,
      clip: 'next station.turnpike lane',
      text: 'The next station is Turnpike Lane.',
      screenText: 'The next station is Turnpike Lane',
      duration: 2.816,
    },
    destination: {
      specId: 709,
      clip: 'destination.turnpike lane',
      text: 'This is a Piccadilly Line service to Turnpike Lane.',
      screenText: 'Piccadilly Line to Turnpike Lane',
      duration: 3.936,
    },
  },
  {
    number: 10,
    name: 'Manor House',
    atStation: {
      specId: 110,
      clip: 'this station.manor house',
      text: 'This is Manor House.',
      screenText: 'This is Manor House',
      duration: 1.952,
    },
    approaching: {
      specId: 210,
      clip: 'next station.manor house',
      text: 'The next station is Manor House.',
      screenText: 'The next station is Manor House',
      duration: 2.752,
    },
    destination: {
      specId: 710,
      clip: 'destination.manor house',
      text: 'This is a Piccadilly Line service to Manor House.',
      screenText: 'Piccadilly Line to Manor House',
      duration: 3.872,
    },
  },
  {
    number: 11,
    name: 'Finsbury Park',
    atStation: {
      specId: 111,
      clip: 'this station.finsbury park',
      text: 'This is Finsbury Park.',
      screenText: 'This is Finsbury Park',
      duration: 1.952,
    },
    approaching: {
      specId: 211,
      clip: 'next station.finsbury park',
      text: 'The next station is Finsbury Park.',
      screenText: 'The next station is Finsbury Park',
      duration: 2.752,
    },
    destination: {
      specId: 711,
      clip: 'destination.finsbury park',
      text: 'This is a Piccadilly Line service to Finsbury Park.',
      screenText: 'Piccadilly Line to Finsbury Park',
      duration: 3.872,
    },
  },
  {
    number: 12,
    name: 'Arsenal',
    atStation: {
      specId: 112,
      clip: 'this station.arsenal',
      text: 'This is Arsenal.',
      screenText: 'This is Arsenal',
      duration: 1.6,
    },
    approaching: {
      specId: 212,
      clip: 'next station.arsenal',
      text: 'The next station is Arsenal.',
      screenText: 'The next station is Arsenal',
      duration: 2.4,
    },
    destination: {
      specId: 712,
      clip: 'destination.arsenal',
      text: 'This is a Piccadilly Line service to Arsenal.',
      screenText: 'Piccadilly Line to Arsenal',
      duration: 3.52,
    },
  },
  {
    number: 13,
    name: 'Holloway Road',
    atStation: {
      specId: 113,
      clip: 'this station.holloway road',
      text: 'This is Halloway Road.',
      screenText: 'This is Holloway Road',
      duration: 1.856,
    },
    approaching: {
      specId: 213,
      clip: 'next station.holloway road',
      text: 'The next station is Holloway.',
      screenText: 'The next station is Holloway Road',
      duration: 2.656,
    },
    destination: {
      specId: 713,
      clip: 'destination.holloway road',
      text: 'This is a Piccadilly Line service to Holloway Park.',
      screenText: 'Piccadilly Line to Holloway Road',
      duration: 3.776,
    },
  },
  {
    number: 14,
    name: 'Caledonian Road',
    atStation: {
      specId: 114,
      clip: 'this station.caledonian road',
      text: 'This is Caledonian Road.',
      screenText: 'This is Caledonian Road',
      duration: 2.08,
    },
    approaching: {
      specId: 214,
      clip: 'next station.caledonian road',
      text: 'The next station is Caledonian Road.',
      screenText: 'The next station is Caledonian Road',
      duration: 2.88,
    },
    destination: {
      specId: 714,
      clip: 'destination.caledonian road',
      text: 'This is a Piccadilly Line service to Caledonian Road.',
      screenText: 'Piccadilly Line to Caledonian Road',
      duration: 4.0,
    },
  },
  {
    number: 15,
    name: "King's Cross, St. Pancras",
    atStation: {
      specId: 115,
      clip: 'this station.kings cross st pancras',
      text: "This is King's Cross St. Pancras.",
      screenText: "This is King's Cross, St. Pancras",
      duration: 2.496,
    },
    approaching: {
      specId: 215,
      clip: 'next station.kings cross st pancras',
      text: "The next station is King's Cross St Pancras.",
      screenText: "The next station is King's Cross, St. Pancras",
      duration: 3.296,
    },
    destination: {
      specId: 715,
      clip: 'destination.kings cross st pancras',
      text: "This is a Piccadilly Line service to King's Cross St Pancras.",
      screenText: "Piccadilly Line to King's Cross, St. Pancras",
      duration: 4.416,
    },
  },
  {
    number: 16,
    name: 'Russell Square',
    atStation: {
      specId: 116,
      clip: 'this station.russell square',
      text: 'This is Russell Square.',
      screenText: 'This is Russell Square',
      duration: 1.92,
    },
    approaching: {
      specId: 216,
      clip: 'next station.russell square',
      text: 'The next station is Russell Square.',
      screenText: 'The next station is Russell Square',
      duration: 2.72,
    },
    destination: {
      specId: 716,
      clip: 'destination.russell square',
      text: 'This is a Piccadilly Line service to Russell Square.',
      screenText: 'Piccadilly Line to Russell Square',
      duration: 3.84,
    },
  },
  {
    number: 17,
    name: 'Holborn',
    atStation: {
      specId: 117,
      clip: 'this station.holborn',
      text: 'This is Holborn.',
      screenText: 'This is Holborn',
      duration: 1.632,
    },
    approaching: {
      specId: 217,
      clip: 'next station.holborn',
      text: 'The next station is Holborn.',
      screenText: 'The next station is Holborn',
      duration: 2.432,
    },
    destination: {
      specId: 717,
      clip: 'destination.holborn',
      text: 'This is a Piccadilly Line service to Holborn.',
      screenText: 'Piccadilly Line to Holborn',
      duration: 3.552,
    },
  },
  {
    number: 18,
    name: 'Covent Garden',
    atStation: {
      specId: 118,
      clip: 'this station.covent garden',
      text: 'This is Covent Garden.',
      screenText: 'This is Covent Garden',
      duration: 1.888,
    },
    approaching: {
      specId: 218,
      clip: 'next station.covent garden',
      text: 'The next station is Covent Garden.',
      screenText: 'The next station is Covent Garden',
      duration: 2.688,
    },
    destination: {
      specId: 718,
      clip: 'destination.covent garden',
      text: 'This is a Piccadilly Line service to Covent Garden.',
      screenText: 'Piccadilly Line to Covent Garden',
      duration: 3.808,
    },
  },
  {
    number: 19,
    name: 'Leicester Square',
    atStation: {
      specId: 119,
      clip: 'this station.leicester square',
      text: 'This is Leicester Square.',
      screenText: 'This is Leicester Square',
      duration: 1.856,
    },
    approaching: {
      specId: 219,
      clip: 'next station.leicester square',
      text: 'The next station is Leicester Square.',
      screenText: 'The next station is Leicester Square',
      duration: 2.656,
    },
    destination: {
      specId: 719,
      clip: 'destination.leicester square',
      text: 'This is a Piccadilly Line service to Leicester Square.',
      screenText: 'Piccadilly Line to Leicester Square',
      duration: 3.776,
    },
  },
  {
    number: 20,
    name: 'Piccadilly Circus',
    atStation: {
      specId: 120,
      clip: 'this station.piccadilly circus',
      text: 'This is Piccadilly Circus.',
      screenText: 'This is Piccadilly Circus',
      duration: 2.176,
    },
    approaching: {
      specId: 220,
      clip: 'next station.piccadilly circus',
      text: 'The next station is Piccadilly Circus.',
      screenText: 'The next station is Piccadilly Circus',
      duration: 2.976,
    },
    destination: {
      specId: 720,
      clip: 'destination.piccadilly circus',
      text: 'This is a Piccadilly Line service to Piccadilly Circus.',
      screenText: 'Piccadilly Line to Piccadilly Circus',
      duration: 4.096,
    },
  },
  {
    number: 21,
    name: 'Green Park',
    atStation: {
      specId: 121,
      clip: 'this station.green park',
      text: 'This is Green Park.',
      screenText: 'This is Green Park',
      duration: 1.792,
    },
    approaching: {
      specId: 221,
      clip: 'next station.green park',
      text: 'The next station is Green Park.',
      screenText: 'The next station is Green Park',
      duration: 2.592,
    },
    destination: {
      specId: 721,
      clip: 'destination.green park',
      text: 'This is a Piccadilly Line service to Green Park.',
      screenText: 'Piccadilly Line to Green Park',
      duration: 3.712,
    },
  },
  {
    number: 22,
    name: 'Hyde Park Corner',
    atStation: {
      specId: 122,
      clip: 'this station.hyde park corner',
      text: 'This is Hyde Park Corner.',
      screenText: 'This is Hyde Park Corner',
      duration: 1.952,
    },
    approaching: {
      specId: 222,
      clip: 'next station.hyde park corner',
      text: 'The next station is Hyde Park Corner.',
      screenText: 'The next station is Hyde Park Corner',
      duration: 2.752,
    },
    destination: {
      specId: 722,
      clip: 'destination.hyde park corner',
      text: 'This is a Piccadilly Line service to Hyde Park Corner.',
      screenText: 'Piccadilly Line to Hyde Park Corner',
      duration: 3.872,
    },
  },
  {
    number: 23,
    name: 'Knightsbridge',
    atStation: {
      specId: 123,
      clip: 'this station.knightsbridge',
      text: 'This is Knightsbridge.',
      screenText: 'This is Knightsbridge',
      duration: 1.824,
    },
    approaching: {
      specId: 223,
      clip: 'next station.knightsbridge',
      text: 'The next station is Knights bridge.',
      screenText: 'The next station is Knightsbridge',
      duration: 2.624,
    },
    destination: {
      specId: 723,
      clip: 'destination.knightsbridge',
      text: 'This is a Piccadilly Line service to Knightsbridge.',
      screenText: 'Piccadilly Line to Knightsbridge',
      duration: 3.744,
    },
  },
  {
    number: 24,
    name: 'South Kensington',
    atStation: {
      specId: 124,
      clip: 'this station.south kensington',
      text: 'This is South Kensington.',
      screenText: 'This is South Kensington',
      duration: 2.112,
    },
    approaching: {
      specId: 224,
      clip: 'next station.south kensington',
      text: 'The next station is South Kensington.',
      screenText: 'The next station is South Kensington',
      duration: 2.912,
    },
    destination: {
      specId: 724,
      clip: 'destination.south kensington',
      text: 'This is a Piccadilly Line service to South Kensington.',
      screenText: 'Piccadilly Line to South Kensington',
      duration: 4.032,
    },
  },
  {
    number: 25,
    name: 'Gloucester Road',
    atStation: {
      specId: 125,
      clip: 'this station.gloucester road',
      text: 'This is Gloucester Road.',
      screenText: 'This is Gloucester Road',
      duration: 1.888,
    },
    approaching: {
      specId: 225,
      clip: 'next station.gloucester road',
      text: 'The next station is Gloucester Road.',
      screenText: 'The next station is Gloucester Road',
      duration: 2.688,
    },
    destination: {
      specId: 725,
      clip: 'destination.gloucester road',
      text: 'This is a Piccadilly Line service to Gloucester Road.',
      screenText: 'Piccadilly Line to Gloucester Road',
      duration: 3.808,
    },
  },
  {
    number: 26,
    name: "Earl's Court",
    atStation: {
      specId: 126,
      clip: 'this station.earls court',
      text: "This is Earl's Court.",
      screenText: "This is Earl's Court",
      duration: 1.856,
    },
    approaching: {
      specId: 226,
      clip: 'next station.earls court',
      text: "The next station is Earl's Court.",
      screenText: "The next station is Earl's Court",
      duration: 2.656,
    },
    destination: {
      specId: 726,
      clip: 'destination.earls court',
      text: "This is a Piccadilly Line service to Earl's Court.",
      screenText: "Piccadilly Line to Earl's Court",
      duration: 3.776,
    },
  },
  {
    number: 27,
    name: 'Barons Court',
    atStation: {
      specId: 127,
      clip: 'this station.barons court',
      text: 'This is Barons Court.',
      screenText: 'This is Barons Court',
      duration: 1.952,
    },
    approaching: {
      specId: 227,
      clip: 'next station.barons court',
      text: 'The next station is Barons Court.',
      screenText: 'The next station is Barons Court',
      duration: 2.752,
    },
    destination: {
      specId: 727,
      clip: 'destination.barons court',
      text: 'This is a Piccadilly Line service to Barons Court.',
      screenText: 'Piccadilly Line to Barons Court',
      duration: 3.872,
    },
  },
  {
    number: 28,
    name: 'Hammersmith',
    atStation: {
      specId: 128,
      clip: 'this station.hammersmith',
      text: 'This is Hammersmith',
      screenText: 'This is Hammersmith',
      duration: 1.696,
    },
    approaching: {
      specId: 228,
      clip: 'next station.hammersmith',
      text: 'The next station is Hammersmith.',
      screenText: 'The next station is Hammersmith',
      duration: 2.496,
    },
    destination: {
      specId: 728,
      clip: 'destination.hammersmith',
      text: 'This is a Piccadilly Line service to Hammersmith.',
      screenText: 'Piccadilly Line to Hammersmith',
      duration: 3.616,
    },
  },
  {
    number: 29,
    name: 'Ravenscourt Park',
    atStation: {
      specId: 129,
      clip: 'this station.ravenscourt park',
      text: 'This is Ravenscourt Park.',
      screenText: 'This is Ravenscourt Park',
      duration: 2.144,
    },
    approaching: {
      specId: 229,
      clip: 'next station.ravenscourt park',
      text: 'The next station is Ravenscourt Park.',
      screenText: 'The next station is Ravenscourt Park',
      duration: 2.944,
    },
    destination: {
      specId: 729,
      clip: 'destination.ravenscourt park',
      text: 'This is a Piccadilly Line service to Ravenscourt Park.',
      screenText: 'Piccadilly Line to Ravenscourt Park',
      duration: 4.064,
    },
  },
  {
    number: 30,
    name: 'Stamford Brook',
    atStation: {
      specId: 130,
      clip: 'this station.stamford brook',
      text: 'This is Stamford Brook.',
      screenText: 'This is Stamford Brook',
      duration: 2.048,
    },
    approaching: {
      specId: 230,
      clip: 'next station.stamford brook',
      text: 'The next station is Stamford Brook.',
      screenText: 'The next station is Stamford Brook',
      duration: 2.848,
    },
    destination: {
      specId: 730,
      clip: 'destination.stamford brook',
      text: 'This is a Piccadilly Line service to Stamford Brook.',
      screenText: 'Piccadilly Line to Stamford Brook',
      duration: 3.968,
    },
  },
  {
    number: 31,
    name: 'Turnham Green',
    atStation: {
      specId: 131,
      clip: 'this station.turnham green',
      text: 'This is Turnham Green.',
      screenText: 'This is Turnham Green',
      duration: 1.888,
    },
    approaching: {
      specId: 231,
      clip: 'next station.turnham green',
      text: 'The next station is Turnham Green.',
      screenText: 'The next station is Turnham Green',
      duration: 2.688,
    },
    destination: {
      specId: 731,
      clip: 'destination.turnham green',
      text: 'This is a Piccadilly Line service to Turnham Green.',
      screenText: 'Piccadilly Line to Turnham Green',
      duration: 3.808,
    },
  },
  {
    number: 32,
    name: 'Chiswick Park',
    atStation: {
      specId: 132,
      clip: 'this station.chiswick park',
      text: 'This is Chiswick Park.',
      screenText: 'This is Chiswick Park',
      duration: 1.92,
    },
    approaching: {
      specId: 232,
      clip: 'next station.chiswick park',
      text: 'The next station is Chiswick Park.',
      screenText: 'The next station is Chiswick Park',
      duration: 2.72,
    },
    destination: {
      specId: 732,
      clip: 'destination.chiswick park',
      text: 'This is a Piccadilly Line service to Chiswick Park.',
      screenText: 'Piccadilly Line to Chiswick Park',
      duration: 3.84,
    },
  },
  {
    number: 33,
    name: 'Acton Town',
    atStation: {
      specId: 133,
      clip: 'this station.acton town',
      text: 'This is Acton Town.',
      screenText: 'This is Acton Town',
      duration: 1.92,
    },
    approaching: {
      specId: 233,
      clip: 'next station.acton town',
      text: 'The next station is Acton Park.',
      screenText: 'The next station is Acton Town',
      duration: 2.72,
    },
    destination: {
      specId: 733,
      clip: 'destination.acton town',
      text: 'This is a Piccadilly Line service to Acton Town.',
      screenText: 'Piccadilly Line to Acton Town',
      duration: 3.84,
    },
  },
  {
    number: 34,
    name: 'South Ealing',
    atStation: {
      specId: 134,
      clip: 'this station.south ealing',
      text: 'This is South Ealing.',
      screenText: 'This is South Ealing',
      duration: 1.888,
    },
    approaching: {
      specId: 234,
      clip: 'next station.south ealing',
      text: 'The next station is South Ealing.',
      screenText: 'The next station is South Ealing',
      duration: 2.688,
    },
    destination: {
      specId: 734,
      clip: 'destination.south ealing',
      text: 'This is a Piccadilly Line service to South Ealing.',
      screenText: 'Piccadilly Line to South Ealing',
      duration: 3.808,
    },
  },
  {
    number: 35,
    name: 'Northfields',
    atStation: {
      specId: 135,
      clip: 'this station.northfields',
      text: 'This is Northfields.',
      screenText: 'This is Northfields',
      duration: 1.952,
    },
    approaching: {
      specId: 235,
      clip: 'next station.northfields',
      text: 'The next station is Northfields.',
      screenText: 'The next station is Northfields',
      duration: 2.752,
    },
    destination: {
      specId: 735,
      clip: 'destination.northfields',
      text: 'This is a Piccadilly Line service to Northfields.',
      screenText: 'Piccadilly Line to Northfields',
      duration: 3.872,
    },
  },
  {
    number: 37,
    name: 'Boston Manor',
    atStation: {
      specId: 137,
      clip: 'this station.boston manor',
      text: 'This is Boston Manor.',
      screenText: 'This is Boston Manor',
      duration: 1.92,
    },
    approaching: {
      specId: 237,
      clip: 'next station.boston manor',
      text: 'The next station is Boston Manor.',
      screenText: 'The next station is Boston Manor',
      duration: 2.72,
    },
    destination: {
      specId: 737,
      clip: 'destination.boston manor',
      text: 'This is a Piccadilly Line service to Boston Manor.',
      screenText: 'Piccadilly Line to Boston Manor',
      duration: 3.84,
    },
  },
  {
    number: 38,
    name: 'Osterley',
    atStation: {
      specId: 138,
      clip: 'this station.osterley',
      text: 'This is Osterley.',
      screenText: 'This is Osterley',
      duration: 1.696,
    },
    approaching: {
      specId: 238,
      clip: 'next station.osterley',
      text: 'The next station is Osterley.',
      screenText: 'The next station is Osterley',
      duration: 2.496,
    },
    destination: {
      specId: 738,
      clip: 'destination.osterley',
      text: 'This is a Piccadilly Line service to Osterley.',
      screenText: 'Piccadilly Line to Osterley',
      duration: 3.616,
    },
  },
  {
    number: 39,
    name: 'Hounslow East',
    atStation: {
      specId: 139,
      clip: 'this station.hounslow east',
      text: 'This is Hounslow East.',
      screenText: 'This is Hounslow East',
      duration: 1.952,
    },
    approaching: {
      specId: 239,
      clip: 'next station.hounslow east',
      text: 'The next station is Hounslow East.',
      screenText: 'The next station is Hounslow East',
      duration: 2.752,
    },
    destination: {
      specId: 739,
      clip: 'destination.hounslow east',
      text: 'This is a Piccadilly Line service to Hounslow East.',
      screenText: 'Piccadilly Line to Hounslow East',
      duration: 3.872,
    },
  },
  {
    number: 40,
    name: 'Hounslow Central',
    atStation: {
      specId: 140,
      clip: 'this station.hounslow central',
      text: 'This is Hounslow Central.',
      screenText: 'This is Hounslow Central',
      duration: 2.016,
    },
    approaching: {
      specId: 240,
      clip: 'next station.hounslow central',
      text: 'The next station is Hounslow Central.',
      screenText: 'The next station is Hounslow Central',
      duration: 2.816,
    },
    destination: {
      specId: 740,
      clip: 'destination.hounslow central',
      text: 'This is a Piccadilly Line service to Hounslow Central.',
      screenText: 'Piccadilly Line to Hounslow Central',
      duration: 3.936,
    },
  },
  {
    number: 41,
    name: 'Hounslow West',
    atStation: {
      specId: 141,
      clip: 'this station.hounslow west',
      text: 'This is Hounslow West.',
      screenText: 'This is Hounslow West',
      duration: 2.016,
    },
    approaching: {
      specId: 241,
      clip: 'next station.hounslow west',
      text: 'The next station is Hounslow West.',
      screenText: 'The next station is Hounslow West',
      duration: 2.816,
    },
    destination: {
      specId: 741,
      clip: 'destination.hounslow west',
      text: 'This is a Piccadilly Line service to Hounslow West.',
      screenText: 'Piccadilly Line to Hounslow West',
      duration: 3.936,
    },
  },
  {
    number: 42,
    name: 'Hatton Cross',
    atStation: {
      specId: 142,
      clip: 'this station.hatton cross',
      text: 'This is Hatton Cross.',
      screenText: 'This is Hatton Cross',
      duration: 1.856,
    },
    approaching: {
      specId: 242,
      clip: 'next station.hatton cross',
      text: 'The next station is Hatton Cross.',
      screenText: 'The next station is Hatton Cross',
      duration: 2.656,
    },
    destination: {
      specId: 742,
      clip: 'destination.hatton cross',
      text: 'This is a Piccadilly Line service to Hatton Cross.',
      screenText: 'Piccadilly Line to Hatton Cross',
      duration: 3.776,
    },
  },
  {
    number: 43,
    name: 'Heathrow Terminal 4',
    atStation: {
      specId: 143,
      clip: 'this station.heathrow terminal 4',
      text: 'This is Heathrow Terminal 4.',
      screenText: 'This is Heathrow Terminal 4',
      duration: 2.336,
    },
    approaching: {
      specId: 243,
      clip: 'next station.heathrow terminal 4',
      text: 'The next station is Heathrow Terminal 4',
      screenText: 'The next station is Heathrow Terminal 4',
      duration: 3.136,
    },
    destination: {
      specId: 743,
      clip: 'destination.heathrow terminal 4',
      text: 'This is a Piccadilly Line service to Heathrow Terminal 4.',
      screenText: 'Piccadilly Line to Heathrow Terminal 4',
      duration: 4.256,
    },
  },
  {
    number: 44,
    name: 'Heathrow Terminals 1,2 and 3',
    atStation: {
      specId: 144,
      clip: 'this station.heathrow terminals 1 2 and 3',
      text: 'This is Heathrow Terminals 1, 2 and 3.',
      screenText: 'This is Heathrow Terminals 1,2 and 3',
      duration: 3.2,
    },
    approaching: {
      specId: 244,
      clip: 'next station.heathrow terminals 1 2 and 3',
      text: 'The next station is Heathrow Terminals 1, 2, and 3',
      screenText: 'The next station is Heathrow Terminals 1,2 and 3',
      duration: 4.0,
    },
    destination: {
      specId: 744,
      clip: 'destination.heathrow terminals 1 2 and 3',
      text: 'This is a Piccadilly Line service to Heathrow Terminals 1, 2 and 3.',
      screenText: 'Piccadilly Line to Heathrow Terminals 1,2 and 3',
      duration: 5.12,
    },
  },
  {
    number: 45,
    name: 'Heathrow Terminal 5',
    atStation: {
      specId: 145,
      clip: 'this station.heathrow terminal 5',
      text: 'This is Heathrow Terminal 5.',
      screenText: 'This is Heathrow Terminal 5',
      duration: 2.432,
    },
    approaching: {
      specId: 245,
      clip: 'next station.heathrow terminal 5',
      text: 'The next station is Heathrow Terminal 5',
      screenText: 'The next station is Heathrow Terminal 5',
      duration: 3.232,
    },
    destination: {
      specId: 745,
      clip: 'destination.heathrow terminal 5',
      text: 'This is a Piccadilly Line service to Heathrow Terminal 5.',
      screenText: 'Piccadilly Line to Heathrow Terminal 5',
      duration: 4.352,
    },
  },
  {
    number: 46,
    name: 'Ealing Common',
    atStation: {
      specId: 146,
      clip: 'this station.ealing common',
      text: 'This is Ealing Common.',
      screenText: 'This is Ealing Common',
      duration: 1.92,
    },
    approaching: {
      specId: 246,
      clip: 'next station.ealing common',
      text: 'The next station is Ealing Common.',
      screenText: 'The next station is Ealing Common',
      duration: 2.72,
    },
    destination: {
      specId: 746,
      clip: 'destination.ealing common',
      text: 'This is a Piccadilly Line service to Ealing Common.',
      screenText: 'Piccadilly Line to Ealing Common',
      duration: 3.84,
    },
  },
  {
    number: 47,
    name: 'Ealing Broadway',
    atStation: {
      specId: 147,
      clip: 'this station.ealing broadway',
      text: 'This is Ealing Broadway.',
      screenText: 'This is Ealing Broadway',
      duration: 2.016,
    },
    approaching: {
      specId: 247,
      clip: 'next station.ealing broadway',
      text: 'The next station is Ealing Broadway.',
      screenText: 'The next station is Ealing Broadway',
      duration: 2.816,
    },
    destination: {
      specId: 747,
      clip: 'destination.ealing broadway',
      text: 'This is a Piccadilly Line service to Ealing Broadway.',
      screenText: 'Piccadilly Line to Ealing Broadway',
      duration: 3.936,
    },
  },
  {
    number: 48,
    name: 'North Ealing',
    atStation: {
      specId: 148,
      clip: 'this station.north ealing',
      text: 'This is North Ealing.',
      screenText: 'This is North Ealing',
      duration: 1.856,
    },
    approaching: {
      specId: 248,
      clip: 'next station.north ealing',
      text: 'The next station is North Ealing.',
      screenText: 'The next station is North Ealing',
      duration: 2.656,
    },
    destination: {
      specId: 748,
      clip: 'destination.north ealing',
      text: 'This is a Piccadilly Line service to North Ealing.',
      screenText: 'Piccadilly Line to North Ealing',
      duration: 3.776,
    },
  },
  {
    number: 49,
    name: 'Park Royal',
    atStation: {
      specId: 149,
      clip: 'this station.park royal',
      text: 'This is Park Royal.',
      screenText: 'This is Park Royal',
      duration: 1.76,
    },
    approaching: {
      specId: 249,
      clip: 'next station.park royal',
      text: 'The next station is Park Royal.',
      screenText: 'The next station is Park Royal',
      duration: 2.56,
    },
    destination: {
      specId: 749,
      clip: 'destination.park royal',
      text: 'This is a Piccadilly Line service to Park Royal.',
      screenText: 'Piccadilly Line to Park Royal',
      duration: 3.68,
    },
  },
  {
    number: 50,
    name: 'Alperton',
    atStation: {
      specId: 150,
      clip: 'this station.alperton',
      text: 'This is Alperton.',
      screenText: 'This is Alperton',
      duration: 1.76,
    },
    approaching: {
      specId: 250,
      clip: 'next station.alperton',
      text: 'The next station is Alperton.',
      screenText: 'The next station is Alperton',
      duration: 2.56,
    },
    destination: {
      specId: 750,
      clip: 'destination.alperton',
      text: 'This is a Piccadilly Line service to Alperton.',
      screenText: 'Piccadilly Line to Alperton',
      duration: 3.68,
    },
  },
  {
    number: 51,
    name: 'Sudbury Town',
    atStation: {
      specId: 151,
      clip: 'this station.sudbury town',
      text: 'This is Sudbury Town.',
      screenText: 'This is Sudbury Town',
      duration: 2.016,
    },
    approaching: {
      specId: 251,
      clip: 'next station.sudbury town',
      text: 'The next station is Sudbury Town.',
      screenText: 'The next station is Sudbury Town',
      duration: 2.816,
    },
    destination: {
      specId: 751,
      clip: 'destination.sudbury town',
      text: 'This is a Piccadilly Line service to Sudbury Town.',
      screenText: 'Piccadilly Line to Sudbury Town',
      duration: 3.936,
    },
  },
  {
    number: 52,
    name: 'Sudbury Hill',
    atStation: {
      specId: 152,
      clip: 'this station.sudbury hill',
      text: 'This is Sudbury Hill.',
      screenText: 'This is Sudbury Hill',
      duration: 1.984,
    },
    approaching: {
      specId: 252,
      clip: 'next station.sudbury hill',
      text: 'The next station is Sudbury Hill.',
      screenText: 'The next station is Sudbury Hill',
      duration: 2.784,
    },
    destination: {
      specId: 752,
      clip: 'destination.sudbury hill',
      text: 'This is a Piccadilly Line service to Sudbury Hill.',
      screenText: 'Piccadilly Line to Sudbury Hill',
      duration: 3.904,
    },
  },
  {
    number: 54,
    name: 'South Harrow',
    atStation: {
      specId: 154,
      clip: 'this station.south harrow',
      text: 'This is South Harrow.',
      screenText: 'This is South Harrow',
      duration: 1.952,
    },
    approaching: {
      specId: 254,
      clip: 'next station.south harrow',
      text: 'The next station is South Harrow.',
      screenText: 'The next station is South Harrow',
      duration: 2.752,
    },
    destination: {
      specId: 754,
      clip: 'destination.south harrow',
      text: 'This is a Piccadilly Line service to South Harrow.',
      screenText: 'Piccadilly Line to South Harrow',
      duration: 3.872,
    },
  },
  {
    number: 55,
    name: 'Rayners Lane',
    atStation: {
      specId: 155,
      clip: 'this station.rayners lane',
      text: 'This is Rayners Lane.',
      screenText: 'This is Rayners Lane',
      duration: 1.92,
    },
    approaching: {
      specId: 255,
      clip: 'next station.rayners lane',
      text: 'The next station is Rayners Lane.',
      screenText: 'The next station is Rayners Lane',
      duration: 2.72,
    },
    destination: {
      specId: 755,
      clip: 'destination.rayners lane',
      text: 'This is a Piccadilly Line service to Rayners Lane.',
      screenText: 'Piccadilly Line to Rayners Lane',
      duration: 3.84,
    },
  },
  {
    number: 56,
    name: 'Eastcote',
    atStation: {
      specId: 156,
      clip: 'this station.eastcote',
      text: 'This is Eastcote.',
      screenText: 'This is Eastcote',
      duration: 1.664,
    },
    approaching: {
      specId: 256,
      clip: 'next station.eastcote',
      text: 'The next station is Eastcote.',
      screenText: 'The next station is Eastcote',
      duration: 2.464,
    },
    destination: {
      specId: 756,
      clip: 'destination.eastcote',
      text: 'This is a Piccadilly Line service to Eastcoat.',
      screenText: 'Piccadilly Line to Eastcote',
      duration: 3.584,
    },
  },
  {
    number: 57,
    name: 'Ruislip Manor',
    atStation: {
      specId: 157,
      clip: 'this station.ruislip manor',
      text: 'This is Ruislip Manor.',
      screenText: 'This is Ruislip Manor',
      duration: 1.984,
    },
    approaching: {
      specId: 257,
      clip: 'next station.ruislip manor',
      text: 'The next station is Ruislip Manor.',
      screenText: 'The next station is Ruislip Manor',
      duration: 2.784,
    },
    destination: {
      specId: 757,
      clip: 'destination.ruislip manor',
      text: 'This is a Piccadilly Line service to Ruislip Manor.',
      screenText: 'Piccadilly Line to Ruislip Manor',
      duration: 3.904,
    },
  },
  {
    number: 58,
    name: 'Ruislip',
    atStation: {
      specId: 158,
      clip: 'this station.ruislip',
      text: 'This is Ruislip.',
      screenText: 'This is Ruislip',
      duration: 1.632,
    },
    approaching: {
      specId: 258,
      clip: 'next station.ruislip',
      text: 'The next station is Ruislip.',
      screenText: 'The next station is Ruislip',
      duration: 2.432,
    },
    destination: {
      specId: 758,
      clip: 'destination.ruislip',
      text: 'This is a Piccadilly Line service to Ruislip.',
      screenText: 'Piccadilly Line to Ruislip',
      duration: 3.552,
    },
  },
  {
    number: 60,
    name: 'Ickenham',
    atStation: {
      specId: 160,
      clip: 'this station.ickenham',
      text: 'This is Ickenham.',
      screenText: 'This is Ickenham',
      duration: 1.568,
    },
    approaching: {
      specId: 260,
      clip: 'next station.ickenham',
      text: 'The next station is Ickenham.',
      screenText: 'The next station is Ickenham',
      duration: 2.368,
    },
    destination: {
      specId: 760,
      clip: 'destination.ickenham',
      text: 'This is a Piccadilly Line service to Ickenham.',
      screenText: 'Piccadilly Line to Ickenham',
      duration: 3.488,
    },
  },
  {
    number: 61,
    name: 'Hillingdon',
    atStation: {
      specId: 161,
      clip: 'this station.hillingdon',
      text: 'This is Hillingdon.',
      screenText: 'This is Hillingdon',
      duration: 1.792,
    },
    approaching: {
      specId: 261,
      clip: 'next station.hillingdon',
      text: 'The next station is Hillingdon.',
      screenText: 'The next station is Hillingdon',
      duration: 2.592,
    },
    destination: {
      specId: 761,
      clip: 'destination.hillingdon',
      text: 'This is a Piccadilly Line service to Hillingdon.',
      screenText: 'Piccadilly Line to Hillingdon',
      duration: 3.712,
    },
  },
  {
    number: 63,
    name: 'Uxbridge',
    atStation: {
      specId: 163,
      clip: 'this station.uxbridge',
      text: 'This is Uxbridge.',
      screenText: 'This is Uxbridge',
      duration: 1.792,
    },
    approaching: {
      specId: 263,
      clip: 'next station.uxbridge',
      text: 'The next station is Uxbridge.',
      screenText: 'The next station is Uxbridge',
      duration: 2.592,
    },
    destination: {
      specId: 763,
      clip: 'destination.uxbridge',
      text: 'This is a Piccadilly Line service to Uxbridge.',
      screenText: 'Piccadilly Line to Uxbridge',
      duration: 3.712,
    },
  },
  {
    number: 64,
    name: 'West Kensington',
    atStation: {
      specId: 164,
      clip: 'this station.west kensington',
      text: 'This is West Kensington.',
      screenText: 'This is West Kensington',
      duration: 2.112,
    },
    approaching: {
      specId: 264,
      clip: 'next station.west kensington',
      text: 'The next station is West Kensington',
      screenText: 'The next station is West Kensington',
      duration: 2.912,
    },
    destination: {
      specId: 764,
      clip: 'destination.west kensington',
      text: 'This is a Piccadilly Line service to West Kensington.',
      screenText: 'Piccadilly Line to West Kensington',
      duration: 4.032,
    },
  },
  {
    number: 65,
    name: 'High Street Kensington',
    atStation: {
      specId: 165,
      clip: 'this station.high street kensington',
      text: 'This is High Street Kensington.',
      screenText: 'This is High Street Kensington',
      duration: 2.304,
    },
    approaching: {
      specId: 265,
      clip: 'next station.high street kensington',
      text: 'The next station is High Street Kensington',
      screenText: 'The next station is High Street Kensington',
      duration: 3.104,
    },
    destination: {
      specId: 765,
      clip: 'destination.high street kensington',
      text: 'This is a Piccadilly Line service to High Street Kensington.',
      screenText: 'Piccadilly Line to High Street Kensington',
      duration: 4.224,
    },
  },
  {
    number: 66,
    name: 'Heathrow Terminals 1, 2, 3 and 5',
    atStation: null,
    approaching: null,
    destination: {
      specId: 766,
      clip: 'destination.heathrow terminals 1 2 3 and 5',
      text: 'This is a Piccadilly Line service to Heathrow Terminals 1, 2, 3 and 5.',
      screenText: 'Piccadilly Line to Heathrow Terminals 1, 2, 3 and 5',
      duration: 5.728,
    },
  },
  {
    number: 67,
    name: 'Heathrow Terminals 4 and 1, 2, 3',
    atStation: null,
    approaching: null,
    destination: {
      specId: 767,
      clip: 'destination.heathrow terminals 4 and 1 2 3',
      text: 'This is a Piccadilly Line service to Heathrow Terminals 4 and 1, 2, 3.',
      screenText: 'Piccadilly Line to Heathrow Terminals 4 and 1, 2, 3',
      duration: 5.92,
    },
  },
]

export const InterchangeAtStation: IPiccadillyClip[] = [
  {
    specId: 400,
    clip: 'interchange here.change here for the victoria line and national rail services',
    text: 'Change here for the Victoria Line and National Rail services.',
    screenText: null,
    duration: 4.512,
  },
  {
    specId: 401,
    clip: 'interchange here.change here for the victoria northern hammersmith and city metropolitan and circle lines',
    text: 'Change here for the Victoria, Northern, Hammersmith & City, Metropolitan and Circle Lines; and National and International Rail services.',
    screenText: null,
    duration: 9.28,
  },
  {
    specId: 402,
    clip: 'interchange here.change here for the central line',
    text: 'Change here for the Central Line.',
    screenText: null,
    duration: 2.528,
  },
  {
    specId: 403,
    clip: 'interchange here.change here for the northern line',
    text: 'Change here for the Northern Line.',
    screenText: null,
    duration: 2.528,
  },
  {
    specId: 404,
    clip: 'interchange here.change here for the bakerloo line',
    text: 'Change here for the Bakerloo Line.',
    screenText: null,
    duration: 2.592,
  },
  {
    specId: 405,
    clip: 'interchange here.change here for the jubilee and victoria lines',
    text: 'Change here for the Jubilee and Victoria Lines.',
    screenText: null,
    duration: 3.52,
  },
  {
    specId: 406,
    clip: 'interchange here.change here for the district and circles lines',
    text: 'Change here for the District and Circles Lines.',
    screenText: null,
    duration: 3.168,
  },
  {
    specId: 407,
    clip: 'interchange here.change here for the circle line',
    text: 'Change here for the Circle Line.',
    screenText: null,
    duration: 2.496,
  },
  {
    specId: 408,
    clip: 'interchange here.change here for the district line',
    text: 'Change here for the District Line.',
    screenText: null,
    duration: 2.624,
  },
  {
    specId: 409,
    clip: 'interchange here.change here for the district and hammersmith and city lines',
    text: 'Change here for the District and Hammersmith & City Lines.',
    screenText: null,
    duration: 4.032,
  },
  {
    specId: 410,
    clip: 'interchange here.change here for the district line and piccadilly line services to other destinations',
    text: 'Change here for the District Line and Piccadilly Line services to other destinations.',
    screenText: null,
    duration: 5.76,
  },
  {
    specId: 411,
    clip: 'interchange here.customers for central london should wait on this platform for a train to arnos grove',
    text: 'Customers for Central London should wait on this platform for a train to Arnos Grove, Oakwood or Cockfosters via Central London.',
    screenText: null,
    duration: 9.344,
  },
  {
    specId: 412,
    clip: 'interchange here.customers for central london should cross the platform for a train to arnos grove oakwood',
    text: 'Customers for Central London should cross the platform for a train to Arnos Grove, Oakwood or Cockfosters via Central London.',
    screenText: null,
    duration: 9.472,
  },
  {
    specId: 413,
    clip: 'interchange here.customers for heathrow terminals 1 2 and 3 should change here and wait on this platform',
    text: 'Customers for Heathrow Terminals 1, 2 and 3 should change here and wait on this platform for a train to Terminals 1, 2 and 3.',
    screenText: null,
    duration: 9.44,
  },
  {
    specId: 414,
    clip: 'interchange here.customers for central london should change here and wait on this platform for a train to',
    text: 'Customers for Central London should change here and wait on this platform for a train to Arnos Grove, Oakwood or Cockfosters via Central London.',
    screenText: null,
    duration: 10.592,
  },
  {
    specId: 415,
    clip: 'interchange here.customers for heathrow terminals 1 2 3 and 5 should change here and wait on this platform',
    text: 'Customers for Heathrow Terminals 1, 2, 3 and 5 should change here and wait on this platform for a train to Terminals 1, 2, 3 and 5.',
    screenText: null,
    duration: 10.624,
  },
  {
    specId: 416,
    clip: 'interchange here.customers for heathrow terminal 4 should change here and wait on this platform for a',
    text: 'Customers for Heathrow Terminal 4 should change here and wait on this platform for a train to Terminal 4.',
    screenText: null,
    duration: 7.744,
  },
  {
    specId: 417,
    clip: 'interchange here.customers for heathrow terminal 5 should change here and wait on this platform for a',
    text: 'Customers for Heathrow Terminal 5 should change here and wait on this platform for a train to Terminals 1, 2, 3 and 5.',
    screenText: null,
    duration: 9.248,
  },
  {
    specId: 418,
    clip: 'interchange here.change here for the metropolitan line',
    text: 'Change here for the Metropolitan Line.',
    screenText: null,
    duration: 2.816,
  },
  {
    specId: 419,
    clip: 'interchange here.change here for the district and hammersmith and city lines the next station is turnham',
    text: 'Change here for the District and Hammersmith & City Lines. The next station is Turnham Green.',
    screenText: null,
    duration: 6.72,
  },
  {
    specId: 420,
    clip: 'interchange here.change here for the district line and piccadilly line services to other destinations the 420',
    text: 'Change here for the District Line and Piccadilly Line services to other destinations. The next station is Turnham Green.',
    screenText: null,
    duration: 8.448,
  },
  {
    specId: 421,
    clip: 'interchange here.change here for the district and hammersmith and city lines the next station is acton town',
    text: 'Change here for the District and Hammersmith and City Lines. The next station is Acton Town.',
    screenText: null,
    duration: 6.752,
  },
  {
    specId: 422,
    clip: 'interchange here.change here for the district line and piccadilly line services to other destinations the 422',
    text: 'Change here for the District Line and Piccadilly Line services to other destinations. The next station is Hammersmith.',
    screenText: null,
    duration: 8.256,
  },
  {
    specId: 423,
    clip: 'interchange here.the next station is heathrow terminals 1 2 and 3 this train may remain here a short time',
    text: 'The next station is Heathrow Terminals 1, 2 and 3. This train may remain here a short time before departure.',
    screenText: null,
    duration: 7.36,
  },
  {
    specId: 424,
    clip: 'interchange here.customers for heathrow terminal 4 should change across platform at this station for a',
    text: 'Customers for Heathrow Terminal 4 should change across platform at this station for a train to Terminals 4 and 1, 2, 3.',
    screenText: null,
    duration: 9.12,
  },
  {
    specId: 425,
    clip: 'interchange here.change here for the victoria line',
    text: 'Change here for the Victoria Line.',
    screenText: null,
    duration: 2.688,
  },
]

export const InterchangeApproaching: IPiccadillyClip[] = [
  {
    specId: 450,
    clip: 'interchange next.change for the victoria line and national rail services',
    text: 'Change for the Victoria Line and National Rail services.',
    screenText: null,
    duration: 4.256,
  },
  {
    specId: 451,
    clip: 'interchange next.change for the victoria northern hammersmith and city metropolitan and circle lines and',
    text: 'Change for the Victoria, Northern, Hammersmith & City, Metropolitan and Circle Lines; and National and International Rail services.',
    screenText: null,
    duration: 9.024,
  },
  {
    specId: 452,
    clip: 'interchange next.change for the central line',
    text: 'Change for the Central Line.',
    screenText: null,
    duration: 2.272,
  },
  {
    specId: 453,
    clip: 'interchange next.change for the northern line',
    text: 'Change for the Northern Line.',
    screenText: null,
    duration: 2.272,
  },
  {
    specId: 454,
    clip: 'interchange next.change for the bakerloo line',
    text: 'Change for the Bakerloo Line.',
    screenText: null,
    duration: 2.336,
  },
  {
    specId: 455,
    clip: 'interchange next.change for the jubilee and victoria lines',
    text: 'Change for the Jubilee and Victoria Lines.',
    screenText: null,
    duration: 3.264,
  },
  {
    specId: 456,
    clip: 'interchange next.change for the district and circle lines',
    text: 'Change for the District and Circle Lines.',
    screenText: null,
    duration: 2.912,
  },
  {
    specId: 457,
    clip: 'interchange next.change for the circle line',
    text: 'Change for the Circle Line.',
    screenText: null,
    duration: 2.24,
  },
  {
    specId: 458,
    clip: 'interchange next.change for the district line',
    text: 'Change for the District Line.',
    screenText: null,
    duration: 2.368,
  },
  {
    specId: 459,
    clip: 'interchange next.change for the district and hammersmith and city lines',
    text: 'Change for the District and Hammersmith & City Lines.',
    screenText: null,
    duration: 3.776,
  },
  {
    specId: 460,
    clip: 'interchange next.change for the district line and piccadilly line services to other destinations',
    text: 'Change for the District Line and Piccadilly Line services to other destinations.',
    screenText: null,
    duration: 5.504,
  },
  {
    specId: 461,
    clip: 'interchange next.customers for central london should wait for a train to arnos grove oakwood or',
    text: 'Customers for Central London should wait for a train to Arnos Grove, Oakwood or Cockfosters via Central London.',
    screenText: null,
    duration: 8.768,
  },
  {
    specId: 462,
    clip: 'interchange next.this train is for hatton cross only customers for central london should cross the',
    text: 'This train is for Hatton Cross only. Customers for Central London should cross the platform for a train to Anos Grove, Oakwood or Cockfosters via Central London.',
    screenText: null,
    duration: 12.096,
  },
  {
    specId: 463,
    clip: 'interchange next.this train is for heathrow terminal 4 customers for heathrow terminals 1 2 and 3 should',
    text: 'This train is for Heathrow Terminal 4. Customers for Heathrow Terminals 1, 2 and 3 should change here and wait for a train to Terminals 1, 2 and 3.',
    screenText: null,
    duration: 11.488,
  },
  {
    specId: 464,
    clip: 'interchange next.this train is for heathrow terminal 4 customers for heathrow terminals 1 2 3 and 5 should',
    text: 'This train is for Heathrow Terminal 4. Customers for Heathrow Terminals 1, 2, 3 and 5 should change here and wait for a train to Terminals 1, 2, 3 and 5.',
    screenText: null,
    duration: 12.672,
  },
  {
    specId: 465,
    clip: 'interchange next.this train is for osterley customers for central london should change here and wait for a',
    text: 'This train is for Osterley. Customers for Central London should change here and wait for a train to Arnos Grove, Oakwood or Cockfosters via Central London.',
    screenText: null,
    duration: 12.0,
  },
  {
    specId: 466,
    clip: 'interchange next.this train is for heathrow terminals 1 2 and 3',
    text: 'This train is for Heathrow Terminals 1, 2 and 3.',
    screenText: null,
    duration: 3.744,
  },
  {
    specId: 467,
    clip: 'interchange next.this train is for heathrow terminals 1 2 and 3 customer for heathrow terminal 4 should',
    text: 'This train is for Heathrow Terminals 1, 2 and 3. Customer for Heathrow Terminal 4 should change here and wait for a train to Terminal 4.',
    screenText: null,
    duration: 10.656,
  },
  {
    specId: 468,
    clip: 'interchange next.this train is going to heathrow terminals 1 2 3 and 5 customers for heathrow terminal 4',
    text: 'This train is going to Heathrow Terminals 1, 2, 3 and 5. Customers for Heathrow Terminal 4 should change here and wait for a train to Terminal 4.',
    screenText: null,
    duration: 11.488,
  },
  {
    specId: 469,
    clip: 'interchange next.this train is going to terminal 1 2 3 via terminal 4',
    text: 'This train is going to Terminal 1, 2, 3 via Terminal 4.',
    screenText: null,
    duration: 5.44,
  },
  {
    specId: 470,
    clip: 'interchange next.this train is going to heathrow terminals 4 and 1 2 3 customers for heathrow terminal 5',
    text: 'This train is going to Heathrow Terminals 4 and 1, 2, 3. Customers for Heathrow Terminal 5 should change here and wait for a train to Terminals 1, 2, 3 and 5.',
    screenText: null,
    duration: 13.184,
  },
  {
    specId: 471,
    clip: 'interchange next.change for the metropolitan line',
    text: 'Change for the Metropolitan Line.',
    screenText: null,
    duration: 2.56,
  },
  {
    specId: 472,
    clip: 'interchange next.customers for heathrow terminal 4 should change across platform at hatton cross for a',
    text: 'Customers for Heathrow Terminal 4 should change across platform at Hatton Cross for a train to Terminals 4 and 1, 2, 3.',
    screenText: null,
    duration: 9.024,
  },
  {
    specId: 473,
    clip: 'interchange next.change for the victoria line',
    text: 'Change for the Victoria Line.',
    screenText: null,
    duration: 2.432,
  },
]

export const LocalInfoAtStation: IPiccadillyClip[] = [
  {
    specId: 600,
    clip: 'local here.alight here for the royal national institute of the blind',
    text: 'Alight here for the Royal National Institute of the Blind.',
    screenText: null,
    duration: 3.776,
  },
  {
    specId: 601,
    clip: 'local here.alight here for the british museum',
    text: 'Alight here for the British Museum.',
    screenText: null,
    duration: 2.56,
  },
  {
    specId: 602,
    clip: 'local here.alight here for londons transport museum',
    text: "Alight here for London's Transport Museum.",
    screenText: null,
    duration: 3.04,
  },
  {
    specId: 603,
    clip: 'local here.alight here for buckingham palace',
    text: 'Alight here for Buckingham Palace.',
    screenText: null,
    duration: 2.4,
  },
  {
    specId: 605,
    clip: 'local here.alight here for the museums and the royal albert hall',
    text: 'Alight here for the Museums and the Royal Albert Hall.',
    screenText: null,
    duration: 3.488,
  },
  {
    specId: 606,
    clip: 'local here.alight here for earls court exhibition centre',
    text: "Alight here for Earl's Court Exhibition Centre.",
    screenText: null,
    duration: 2.944,
  },
]

export const LocalInfoApproaching: IPiccadillyClip[] = [
  {
    specId: 650,
    clip: 'local next.alight for the royal national institute of the blind',
    text: 'Alight for the Royal National Institute of the Blind.',
    screenText: null,
    duration: 3.552,
  },
  {
    specId: 651,
    clip: 'local next.alight for the british museum',
    text: 'Alight for the British Museum.',
    screenText: null,
    duration: 2.336,
  },
  {
    specId: 652,
    clip: 'local next.alight for londons transport museum',
    text: "Alight for London's Transport Museum.",
    screenText: null,
    duration: 2.816,
  },
  {
    specId: 653,
    clip: 'local next.alight for buckingham palace',
    text: 'Alight for Buckingham Palace.',
    screenText: null,
    duration: 2.176,
  },
  {
    specId: 655,
    clip: 'local next.alight for the museums and the royal albert hall',
    text: 'Alight for the Museums and the Royal Albert Hall.',
    screenText: null,
    duration: 3.264,
  },
  {
    specId: 656,
    clip: 'local next.alight for earls court exhibition and the royal albert hall',
    text: "Alight for Earl's Court Exhibition and the Royal Albert Hall.",
    screenText: null,
    duration: 2.72,
  },
]

export const SafetyAnnouncements: IPiccadillyClip[] = [
  {
    specId: 500,
    clip: 'safety.please mind the gap between the train and the platform',
    text: 'Please mind the gap between the train and the platform.',
    screenText: null,
    duration: 3.008,
  },
  {
    specId: 501,
    clip: 'safety.please remember to keep all your personal belongings with you at all times',
    text: 'Please remember to keep all your personal belongings with you at all times.',
    screenText: null,
    duration: 3.744,
  },
]

export const GeneralAnnouncements: IPiccadillyClip[] = [
  {
    specId: 1,
    clip: 'general.please stand clear of the doors',
    text: 'Please stand clear of the doors.',
    screenText: 'Please stand clear of the doors',
    duration: 1.728,
  },
  {
    specId: 2,
    clip: 'general.let customers off the train first please',
    text: 'Let customers off the train first please.',
    screenText: 'Let customers off first please',
    duration: 2.528,
  },
  {
    specId: 3,
    clip: 'general.please move right down inside the cars',
    text: 'Please move right down inside the cars.',
    screenText: 'Please move right down inside the cars',
    duration: 2.176,
  },
  {
    specId: 4,
    clip: 'general.please mind the gap between the train and the platform',
    text: 'Please mind the gap between the train and the platform.',
    screenText: 'Please mind the gap between the train and the platform',
    duration: 3.008,
  },
  {
    specId: 5,
    clip: 'general.this train terminates here all change please ensure that you take all your personal 005',
    text: 'This train terminates here. All change. Please ensure that you take all your personal belongings with you.',
    screenText: 'This train terminates here. All change.Please ensure that you take all your personal belongings with you',
    duration: 6.016,
  },
  {
    specId: 6,
    clip: 'general.please remember to keep all your personal belongings with you at all times',
    text: 'Please remember to keep all your personal belongings with you at all times.',
    screenText: 'Please remember to keep all your personal belongings with you at all times',
    duration: 3.744,
  },
  {
    specId: 7,
    clip: 'general.please remember to keep all your personal belongings with you at all times report any',
    text: 'Please remember to keep all your personal belongings with you at all times. Report any unattended item or suspicious behaviour to a member of staff or a police officer.',
    screenText:
      'Please remember to keep all your personal belongings with you at all times. Report any unattended item or suspicious behaviour to a member of staff or a police officer',
    duration: 9.728,
  },
  {
    specId: 8,
    clip: 'general.the next station is closed',
    text: 'The next station is closed.',
    screenText: 'The next station is closed',
    duration: 1.952,
  },
  {
    specId: 9,
    clip: 'general.because of a security alert the next station has been closed and evacuated piccadilly',
    text: 'Because of a security alert, the next station has been closed and evacuated. Piccadilly Line trains will not stop.',
    screenText: 'Because of a security alert, the next station has been closed and evacuated. Piccadilly Line trains will not stop',
    duration: 7.136,
  },
  {
    specId: 10,
    clip: 'general.heathrow terminal 4 station is closed this train will terminate at heathrow terminals 1 2',
    text: 'Heathrow Terminal 4 station is closed. This train will terminate at Heathrow Terminals 1, 2 and 3.',
    screenText: 'Heathrow Terminal 4 station is closed.This train will terminate at Heathrow Terminals 1, 2 and 3',
    duration: 7.232,
  },
  {
    specId: 11,
    clip: 'general.because of a security alert at terminal 4 station this train will call at heathrow',
    text: 'Because of a security alert at Terminal 4 station, this train will call at Heathrow Terminals 1, 2 and 3 only. Customers for Terminal 4 should remain on this on this train to Heathrow Terminals 1, 2 and 3 where alternative transfer arrangements will be made.',
    screenText:
      'Because of a security alert at Terminal 4 station, this train will call at Heathrow Terminals 1, 2 and 3 only. Customers for Terminal 4 should remain on this train to Heathrow Terminals 1, 2 and 3 where alternative transfer arrangements',
    duration: 15.808,
  },
  {
    specId: 12,
    clip: 'general.heathrow terminal 5 station is closed this train will terminate at heathrow at heathrow',
    text: 'Heathrow Terminal 5 station is closed. This train will terminate at Heathrow at Heathrow Terminals 1, 2 and 3.',
    screenText: 'Heathrow Terminal 5 station is closed. This train will terminate at Heathrow Terminals 1, 2 and 3.',
    duration: 7.008,
  },
  {
    specId: 13,
    clip: 'general.because of a security alert at terminal 5 this train will call at heathrow terminals 1 2',
    text: 'Because of a security alert at Terminal 5, this train will call at Heathrow Terminals 1, 2 and 3 only. Customers for Terminal 5 should remain on this train to Heathrow 1, 2 and 3, where alternative transfer arrangements will be made.',
    screenText:
      'Because of a security alert at Terminal 5 station, this train will call at Heathrow Terminals 1, 2 and 3 only. Customers for Terminal 5 should remain on this train to Heathrow Terminals 1, 2 and 3, where alternative transfer arrangements',
    duration: 15.968,
  },
  {
    specId: 14,
    clip: 'general.heathrow terminals 1 2 and 3 station is closed this train will terminate at heathrow',
    text: 'Heathrow Terminals 1, 2 and 3 station is closed. This train will terminate at Heathrow Terminal 5.',
    screenText: 'Heathrow Terminals 1, 2 and 3 station is closed. This train will terminate at Heathrow Terminal 5.',
    duration: 7.04,
  },
  {
    specId: 15,
    clip: 'general.because of a security alert at terminals 1 2 and 3 station this train will call at',
    text: 'Because of a security alert at Terminals 1, 2 and 3 station, this train will call at Heathrow Terminal 5 only. Customers for Terminal 1, 2 and 3 should remain on this train to Heathrow Terminal 5, where alternative transfer arrangements will be made.',
    screenText:
      'Because of a security alert at Terminals 1, 2 and 3 station, this train will call at Heathrow Terminal 5 only. Customers for Terminals 1, 2 and 3 should remain on this train to Heathrow Terminal 5, where alternative transfer arrangements',
    duration: 16.768,
  },
  {
    specId: 16,
    clip: 'general.there is a restricted lift service at the next station and customers may experience some',
    text: 'There is a restricted lift service at the next station and customers may experience some delay upon leaving the station.',
    screenText: 'There is a restricted lift service at the next station and customers may experience some delay upon leaving the station',
    duration: 6.944,
  },
  {
    specId: 17,
    clip: 'general.there is a restricted escalator service at the next station and customers may experience',
    text: 'There is a restricted escalator service at the next station and customers may experience some delay upon leaving the station.',
    screenText: 'There is a restricted escalator service at the next station and customers may experience some delay upon leaving the station',
    duration: 7.232,
  },
  {
    specId: 18,
    clip: 'general.attention this train is about to move slowly forward and then stop suddenly please use',
    text: 'Attention. This train is about to move slowly forward and then stop suddenly. Please use seats available, or if standing, hold on tight. Following this routine safety procedure we will continue moving at reduced speed.',
    screenText: 'Attention. This train is about to move slowly forward and then stop suddenly. Please hold on tight',
    duration: 13.792,
  },
  {
    specId: 19,
    clip: 'general.this train is being delayed due to signalling difficulties we will keep you informed as',
    text: 'This train is being delayed due to signalling difficulties. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause.',
    screenText:
      'This train is being delayed due to signalling difficulties. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause',
    duration: 10.208,
  },
  {
    specId: 20,
    clip: 'general.this train is being delayed due to technical difficulties we will keep you informed as',
    text: 'This train is being delayed due to technical difficulties. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause.',
    screenText:
      'This train is being delayed due to technical difficulties. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause',
    duration: 10.176,
  },
  {
    specId: 21,
    clip: 'general.this train is being delayed due to adverse weather conditions we will keep you informed',
    text: 'This train is being delayed due to adverse weather conditions. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause.',
    screenText:
      'This train is being delayed due to adverse weather conditions. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause',
    duration: 10.368,
  },
  {
    specId: 22,
    clip: 'general.this train is being delayed due to circumstances beyond our control we will keep you',
    text: 'This train is being delayed due to circumstances beyond our control. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause.',
    screenText:
      'This train is being delayed due to circumstances beyond our control. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause',
    duration: 10.784,
  },
  {
    specId: 23,
    clip: 'general.this train is being delayed due to an incident earlier in the day we will keep you',
    text: 'This train is being delayed due to an incident earlier in the day. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause.',
    screenText:
      'This train is being delayed due to an incident earlier in the day. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause',
    duration: 10.656,
  },
  {
    specId: 24,
    clip: 'general.this train is being delayed due to essential engineering work we will keep you informed',
    text: 'This train is being delayed due to essential engineering work. We will keep you informed as information becomes available. We apologise for any inconvenience this any cause.',
    screenText:
      'This train is being delayed due to essential engineering work. We will keep you informed as information becomes available. We apologise for any inconvenience this may cause',
    duration: 10.496,
  },
  {
    specId: 25,
    clip: 'general.this train will be held here for a short time to even out gaps in the service',
    text: 'This train will be held here for a short time to even out gaps in the service.',
    screenText: 'This train will be held here for a short time to even out the gaps in the service',
    duration: 4.896,
  },
  {
    specId: 26,
    clip: 'general.a passenger alarm has been operated on this train there will be a delay whilst',
    text: 'A passenger alarm has been operated on this train. There will be a delay whilst investigations are made.',
    screenText: 'A passenger alarm has been operated on this train. There will be a delay whilst investigations are made',
    duration: 6.08,
  },
  {
    specId: 27,
    clip: 'general.this train will additionally call at ravenscourt park stamford bridge turnham green and',
    text: 'This train will additionally call at Ravenscourt Park, Stamford Bridge, Turnham Green and Chiswick Park.',
    screenText: 'This train will call additionally at Ravenscourt Park, Stamford Brook, Turnham Green and Chiswick Park',
    duration: 7.296,
  },
  {
    specId: 28,
    clip: 'general.this train will additionally call at chiswick park turnham green stamford brook and',
    text: 'This train will additionally call at Chiswick Park, Turnham Green, Stamford Brook and Ravenscourt Park.',
    screenText: 'This train will call additionally at Chiswick Park, Turnham Green, Stamford Brook and Ravenscourt Park',
    duration: 7.36,
  },
  {
    specId: 29,
    clip: 'general.for safety reasons smoking is not permitted on any part of london underground',
    text: 'For safety reasons, smoking is not permitted on any part of London Underground.',
    screenText: 'For safety reasons, smoking is not permitted on any part of London Underground',
    duration: 4.576,
  },
  {
    specId: 30,
    clip: 'general.there are beggars and buskers operating on this train please do not encourage their',
    text: 'There are beggars and buskers operating on this train. Please do not encourage their presence by supporting them.',
    screenText: 'There are beggars and buskers operating on this train. Please do not encourage their presence by supporting them',
    duration: 5.696,
  },
  {
    specId: 31,
    clip: 'general.this train is not in service 031',
    text: 'This train is not in service.',
    screenText: 'NOT IN SERVICE',
    duration: 2.176,
  },
  {
    specId: 32,
    clip: 'general.this train has a defect and is being withdrawn from service please remain on the platform',
    text: 'This train has a defect and is being withdrawn from service. Please remain on the platform, and await further information. London Underground apologise for any inconvenience caused.',
    screenText:
      'This train has a defect, and is being withdrawn from service. Please remain on the platform, and await further information. London Underground apologise for any inconvenience caused',
    duration: 10.624,
  },
  {
    specId: 33,
    clip: 'general.attention this train and station are now being evacuated please leave the train and',
    text: "Attention. This train and station are now being evacuated. Please leave the train and follow staff's instruction to exit the station.",
    screenText:
      "Attention. This train and station are now being evacuated. Please leave the train and follow staff's instructions to exit the station",
    duration: 7.904,
  },
  {
    specId: 34,
    clip: 'general.attention please leave the train now please leave the train now',
    text: 'Attention. Please leave the train now. Please leave the train now.',
    screenText: 'Attention. Please leave the train now. Please leave the train now',
    duration: 4.064,
  },
  {
    specId: 73,
    clip: 'general.this train is not in service 073',
    text: 'This train is not in service.',
    screenText: 'NOT IN SERVICE',
    duration: 2.176,
  },
  {
    specId: 301,
    clip: 'general.this train will terminate here all change please ensure that you take all your personal',
    text: 'This train will terminate here. All change. Please ensure that you take all your personal belongings with you.',
    screenText: 'This train will terminate.',
    duration: 6.304,
  },
  {
    specId: 302,
    clip: 'general.this train terminates here all change please ensure that you take all your personal 302',
    text: 'This train terminates here. All change. Please ensure that you take all your personal belongings with you.',
    screenText: 'Train terminates here.',
    duration: 6.016,
  },
]

export const EngineeringAnnouncements: IPiccadillyClip[] = [
  {
    specId: 98,
    clip: 'engineering.sign test test complete',
    text: 'Sign Test. Test Complete!',
    screenText: 'Sign test.Test Complete!',
    duration: 2.272,
  },
  {
    specId: 99,
    clip: 'engineering.walk through',
    text: 'WALK THROUGH',
    screenText: 'WALK THROUGH',
    duration: 0.96,
  },
  {
    specId: 901,
    clip: 'engineering.system sound test',
    text: 'System Sound Test',
    screenText: 'System Sound Test',
    duration: 300.16,
  },
  {
    specId: 902,
    clip: 'engineering.speaker impedance test',
    text: 'Speaker Impedance Test',
    screenText: 'Speaker Impedance Test',
    duration: 9.696,
  },
  {
    specId: 903,
    clip: 'engineering.mlssa performance test',
    text: 'MLSSA Performance Test',
    screenText: 'MLSSA Performance Test',
    duration: 60.032,
  },
  {
    specId: 905,
    clip: 'engineering.cab intruder circuit open',
    text: 'Cab intruder circuit open',
    screenText: 'Cab intruder circuit open',
    duration: 2.368,
  },
  {
    specId: 906,
    clip: 'engineering.cab intruder circuit closed',
    text: 'Cab intruder circuit closed',
    screenText: 'Cab intruder circuit closed',
    duration: 2.56,
  },
  {
    specId: 907,
    clip: 'engineering.saloon intruder circuit open',
    text: 'Saloon Intruder circuit open',
    screenText: 'Saloon Intruder circuit open',
    duration: 2.304,
  },
  {
    specId: 908,
    clip: 'engineering.saloon intruder circuit closed',
    text: 'Saloon Intruder circuit closed',
    screenText: 'Saloon Intruder circuit closed',
    duration: 2.4,
  },
  {
    specId: 909,
    clip: 'engineering.pa train wire test silent announcement',
    text: 'PA train wire test - silent announcement',
    screenText: 'PA train wire test - silent announcement',
    duration: 4.064,
  },
  {
    specId: 910,
    clip: 'engineering.alarm handle operated in vestibule',
    text: 'Alarm Handle operated in vestibule..',
    screenText: 'Alarm Handle operated in vestibule..',
    duration: 2.592,
  },
  {
    specId: 911,
    clip: 'engineering.a',
    text: 'A',
    screenText: 'A',
    duration: 0.576,
  },
  {
    specId: 912,
    clip: 'engineering.b',
    text: 'B',
    screenText: 'B',
    duration: 0.576,
  },
  {
    specId: 913,
    clip: 'engineering.c',
    text: 'C',
    screenText: 'C',
    duration: 0.736,
  },
  {
    specId: 914,
    clip: 'engineering.d',
    text: 'D',
    screenText: 'D',
    duration: 0.704,
  },
  {
    specId: 921,
    clip: 'engineering.car',
    text: 'Car..',
    screenText: 'Car..',
    duration: 0.768,
  },
  {
    specId: 922,
    clip: 'engineering.1',
    text: '1',
    screenText: '1',
    duration: 0.768,
  },
  {
    specId: 923,
    clip: 'engineering.2',
    text: '2',
    screenText: '2',
    duration: 0.672,
  },
  {
    specId: 924,
    clip: 'engineering.3',
    text: '3',
    screenText: '3',
    duration: 0.832,
  },
  {
    specId: 925,
    clip: 'engineering.4',
    text: '4',
    screenText: '4',
    duration: 0.768,
  },
  {
    specId: 926,
    clip: 'engineering.5',
    text: '5',
    screenText: '5',
    duration: 0.992,
  },
  {
    specId: 927,
    clip: 'engineering.6',
    text: '6',
    screenText: '6',
    duration: 0.832,
  },
  {
    specId: 928,
    clip: 'engineering.talk back confirmed in car',
    text: 'Talk-back confirmed in car..',
    screenText: 'Talk-back confirmed in car..',
    duration: 2.336,
  },
  {
    specId: 930,
    clip: 'engineering.test announcement 1',
    text: 'Test announcement 1',
    screenText: 'Test announcement 1',
    duration: 5.536,
  },
  {
    specId: 931,
    clip: 'engineering.test announcement 2',
    text: 'Test announcement 2',
    screenText: 'Test announcement 2',
    duration: 6.272,
  },
  {
    specId: 932,
    clip: 'engineering.test announcement 3',
    text: 'Test announcement 3',
    screenText: 'Test announcement 3',
    duration: 6.784,
  },
  {
    specId: 933,
    clip: 'engineering.test announcement 4',
    text: 'Test announcement 4',
    screenText: 'Test announcement 4',
    duration: 6.24,
  },
  {
    specId: 934,
    clip: 'engineering.test announcement 5',
    text: 'Test announcement 5',
    screenText: 'Test announcement 5',
    duration: 6.464,
  },
  {
    specId: 935,
    clip: 'engineering.test announcement 6',
    text: 'Test announcement 6',
    screenText: 'Test announcement 6',
    duration: 6.144,
  },
  {
    specId: 936,
    clip: 'engineering.test announcement 7',
    text: 'Test announcement 7',
    screenText: 'Test announcement 7',
    duration: 8.16,
  },
  {
    specId: 937,
    clip: 'engineering.test announcement 8',
    text: 'Test announcement 8',
    screenText: 'Test announcement 8',
    duration: 6.304,
  },
  {
    specId: 938,
    clip: 'engineering.test announcement 9',
    text: 'Test announcement 9',
    screenText: 'Test announcement 9',
    duration: 5.376,
  },
  {
    specId: 939,
    clip: 'engineering.test announcement 10',
    text: 'Test announcement 10',
    screenText: 'Test announcement 10',
    duration: 9.12,
  },
  {
    specId: 940,
    clip: 'engineering.walk test automatic shutdown warning',
    text: 'Walk Test automatic shutdown warning',
    screenText: 'Walk Test automatic shutdown warning',
    duration: 5.376,
  },
  {
    specId: 941,
    clip: 'engineering.cab alarm operated in car',
    text: 'Cab Alarm operated in car..',
    screenText: 'Cab Alarm operated in car..',
    duration: 2.496,
  },
  {
    specId: 942,
    clip: 'engineering.cab alarm reset in car',
    text: 'Cab Alarm reset in car..',
    screenText: 'Cab Alarm reset in car..',
    duration: 2.176,
  },
]

export const AllClips: IPiccadillyClip[] = [
  ...Stations.flatMap(station => [station.atStation, station.approaching, station.destination]).filter(clip => clip !== null),
  ...InterchangeAtStation,
  ...InterchangeApproaching,
  ...LocalInfoAtStation,
  ...LocalInfoApproaching,
  ...SafetyAnnouncements,
  ...GeneralAnnouncements,
  ...EngineeringAnnouncements,
]
