import json


reasons = [
    "a bicycle on the track earlier on this trains journey",
    "a bicycle on the track earlier today",
    "a bicycle on the track",
    "a boat colliding with a bridge earlier today",
    "a boat colliding with a bridge",
    "a bridge being damaged by a boat",
    "a bridge being damaged by a road vehicle",
    "a bridge being damaged",
    "a bridge having collapsed",
    "a broken down train earlier today",
    "a broken down train",
    "a broken rail",
    "a broken windscreen on the train",
    "a burst water main flooding the railway earlier today",
    "a burst water main flooding the railway",
    "a burst water main near the railway earlier today",
    "a burst water main near the railway yesterday",
    "a burst water main near the railway",
    "a bus colliding with a bridge earlier on this trains journey",
    "a bus colliding with a bridge earlier today",
    "a bus colliding with a bridge",
    "a chemical spillage near the railway earlier today",
    "a chemical spillage near the railway yesterday",
    "a chemical spillage near the railway",
    "a coach becoming uncoupled on a train earlier in its journey",
    "a coach becoming uncoupled on a train earlier today",
    "a coach becoming uncoupled on a train",
    "a coach becoming uncoupled on this train earlier in its journey",
    "a coach becoming uncoupled on this train earlier today",
    "a coach becoming uncoupled on this train",
    "a collision at a level crossing earlier today",
    "a collision at a level crossing yesterday",
    "a collision at a level crossing",
    "a collision between trains",
    "a collision with the buffers at a station",
    "a derailed train",
    "a derailment within the depot",
    "a fault occurring when attaching a part of a train",
    "a fault occurring when attaching a part of this train",
    "a fault occurring when detaching a part of a train",
    "a fault occurring when detaching a part of this train",
    "a fault on a train in front of this one",
    "a fault on this train which is now fixed",
    "a fault on this train",
    "a fault with a swing bridge over a river earlier today",
    "a fault with a swing bridge over a river",
    "a fault with barriers at a level crossing earlier today",
    "a fault with barriers at a level crossing yesterday",
    "a fault with barriers at a level crossing",
    "a fault with the electric third rail earlier on this trains journey",
    "a fault with the electric third rail earlier today",
    "a fault with the electric third rail",
    "a fault with the on-train signalling system earlier on this trains journey",
    "a fault with the on-train signalling system earlier today",
    "a fault with the on-train signalling system",
    "a fault with the radio system between the driver and the signaller earlier on this trains journey",
    "a fault with the radio system between the driver and the signaller earlier today",
    "a fault with the radio system between the driver and the signaller",
    "a fault with the signalling system earlier on this trains journey",
    "a fault with the signalling system earlier today",
    "a fault with the signalling system",
    "a fire at a station earlier",
    "a fire at a station",
    "a fire near the railway involving gas cylinders earlier today",
    "a fire near the railway involving gas cylinders yesterday",
    "a fire near the railway involving gas cylinders",
    "a fire near the railway suspected to involve gas cylinders earlier today",
    "a fire near the railway suspected to involve gas cylinders yesterday",
    "a fire near the railway suspected to involve gas cylinders",
    "a fire next to the track earlier today",
    "a fire next to the track",
    "a fire on a train earlier today",
    "a fire on a train",
    "a fire on property near the railway earlier today",
    "a fire on property near the railway yesterday",
    "a fire on property near the railway",
    "a gas leak near the railway earlier today",
    "a gas leak near the railway yesterday",
    "a gas leak near the railway",
    "a landslip",
    "a late departure while the train was cleaned specially",
    "a late running freight train",
    "a late running train being in front of this one",
    "a lorry colliding with a bridge earlier on this trains journey",
    "a lorry colliding with a bridge earlier today",
    "a lorry colliding with a bridge",
    "a low speed derailment",
    "a member of on-train staff being taken ill",
    "a passenger being taken ill at a station earlier today",
    "a passenger being taken ill at a station",
    "a passenger being taken ill on a train earlier today",
    "a passenger being taken ill on a train",
    "a passenger being taken ill on this train earlier in its journey",
    "a passenger being taken ill on this train",
    "a person being hit by a train earlier",
    "a person being hit by a train",
    "a points failure (new)",
    "a points failure",
    "a power cut at this station",
    "a problem currently under investigation",
    "a problem with a river bridge earlier today",
    "a problem with a river bridge",
    "a problem with lineside equipment",
    "a problem with the station lighting",
    "a rail buckling in the heat",
    "a railway embankment being damaged",
    "a river flooding the railway earlier today",
    "a river flooding the railway",
    "a road accident at a level crossing earlier today",
    "a road accident at a level crossing yesterday",
    "a road accident at a level crossing",
    "a road accident near the railway earlier today",
    "a road accident near the railway yesterday",
    "a road accident near the railway",
    "a road vehicle blocking the railway earlier on this trains journey",
    "a road vehicle blocking the railway earlier today",
    "a road vehicle blocking the railway",
    "a road vehicle colliding with a bridge earlier on this trains journey",
    "a road vehicle colliding with a bridge earlier today",
    "a road vehicle colliding with a bridge",
    "a road vehicle colliding with level crossing barriers earlier today",
    "a road vehicle colliding with level crossing barriers yesterday",
    "a road vehicle colliding with level crossing barriers",
    "a road vehicle damaging track at a level crossing earlier today",
    "a road vehicle damaging track at a level crossing yesterday",
    "a road vehicle damaging track at a level crossing",
    "a safety inspection of the track earlier today",
    "a safety inspection of the track",
    "a safety inspection on a train earlier today",
    "a safety inspection on a train",
    "a safety inspection on this train earlier in its journey",
    "a safety inspection on this train",
    "a security alert at a station",
    "a security alert earlier today",
    "a security alert on another train",
    "a security alert on this train",
    "a security alert",
    "a shortage of on-train staff",
    "a shortage of station staff",
    "a shortage of train conductors",
    "a shortage of train crew",
    "a shortage of train drivers",
    "a shortage of train guards",
    "a shortage of train managers",
    "a shortage of trains because of accident damage",
    "a shortage of trains because of extra safety inspections",
    "a shortage of trains because of vandalism",
    "a shortage of trains following damage by snow and ice",
    "a signalling apparatus failure",
    "a speed restriction because of fog earlier on this trains journey",
    "a speed restriction because of fog earlier today",
    "a speed restriction because of fog",
    "a speed restriction because of heavy rain earlier on this trains journey",
    "a speed restriction because of heavy rain earlier today",
    "a speed restriction because of heavy rain",
    "a speed restriction because of high track temperatures earlier on this trains journey",
    "a speed restriction because of high track temperatures earlier today",
    "a speed restriction because of high track temperatures",
    "a speed restriction because of high winds earlier on this trains journey",
    "a speed restriction because of high winds earlier today",
    "a speed restriction because of high winds",
    "a speed restriction because of severe weather earlier on this trains journey",
    "a speed restriction because of severe weather earlier today",
    "a speed restriction because of severe weather",
    "a speed restriction because of snow and ice earlier on this trains journey",
    "a speed restriction because of snow and ice earlier today",
    "a speed restriction because of snow and ice",
    "a speed restriction earlier on this trains journey",
    "a speed restriction earlier today",
    "a speed restriction in a tunnel earlier on this trains journey",
    "a speed restriction in a tunnel earlier today",
    "a speed restriction in a tunnel",
    "a speed restriction over a bridge earlier on this trains journey",
    "a speed restriction over a bridge earlier today",
    "a speed restriction over a bridge",
    "a speed restriction over an embankment earlier on this trains journey",
    "a speed restriction over an embankment earlier today",
    "a speed restriction over an embankment",
    "a speed restriction over defective track earlier on this trains journey",
    "a speed restriction over defective track earlier today",
    "a speed restriction over defective track",
    "a speed restriction",
    "a staff shortage",
    "a supermarket trolley on the track earlier on this trains journey",
    "a supermarket trolley on the track earlier today",
    "a supermarket trolley on the track",
    "a technical problem",
    "a train being involved in an accident",
    "a train derailment earlier today",
    "a train derailment yesterday",
    "a train failure",
    "a train hitting an obstruction on the line earlier on this trains journey",
    "a train hitting an obstruction on the line earlier today",
    "a train hitting an obstruction on the line",
    "a train not stopping at a station it was supposed to earlier in its journey",
    "a train not stopping at a station it was supposed to earlier today",
    "a train not stopping at a station it was supposed to",
    "a train not stopping in the correct position at a station earlier in its journey",
    "a train not stopping in the correct position at a station earlier today",
    "a train not stopping in the correct position at a station",
    "a trains automatic braking system being activated earlier in its journey",
    "a trains automatic braking system being activated earlier today",
    "a trains automatic braking system being activated",
    "a tree blocking the railway earlier on this trains journey",
    "a tree blocking the railway earlier today",
    "a tree blocking the railway",
    "a tunnel being closed for safety reasons",
    "a wartime bomb near the railway earlier today",
    "a wartime bomb near the railway yesterday",
    "a wartime bomb near the railway",
    "a wartime bomb which has now been made safe",
    "adverse weather conditions",
    "an earlier landslip",
    "an earlier problem with lineside equipment",
    "an incident at the airport",
    "an incident on the line",
    "an object being caught on the overhead electric wires earlier on this trains journey",
    "an object being caught on the overhead electric wires earlier today",
    "an object being caught on the overhead electric wires",
    "an obstruction on the track earlier on this trains journey",
    "an obstruction on the track earlier today",
    "an obstruction on the track",
    "an operational incident earlier in its journey",
    "an operational incident earlier today",
    "an operational incident",
    "animals on the railway earlier today",
    "animals on the railway",
    "attempted theft of overhead line electrification equipment earlier today",
    "attempted theft of overhead line electrification equipment yesterday",
    "attempted theft of overhead line electrification equipment",
    "attempted theft of railway equipment earlier today",
    "attempted theft of railway equipment yesterday",
    "attempted theft of railway equipment",
    "attempted theft of signalling cables earlier today",
    "attempted theft of signalling cables yesterday",
    "attempted theft of signalling cables",
    "attempted theft of third rail electrification equipment earlier today",
    "attempted theft of third rail electrification equipment yesterday",
    "attempted theft of third rail electrification equipment",
    "bad weather conditions",
    "cancellation of the incoming service",
    "cattle on the railway earlier today",
    "cattle on the railway",
    "checking reports of an obstruction on the line earlier on this trains journey",
    "checking reports of an obstruction on the line earlier today",
    "checking reports of an obstruction on the line",
    "congestion",
    "damage to the electric third rail earlier on this trains journey",
    "damage to the electric third rail earlier today",
    "damage to the electric third rail",
    "damage to the overhead electric wires earlier on this trains journey",
    "damage to the overhead electric wires earlier today",
    "damage to the overhead electric wires",
    "due to operational problems",
    "earlier engineering works not being finished on time",
    "engineering work",
    "engineering works not being finished on time",
    "engineering works",
    "expected industrial action earlier today",
    "expected industrial action yesterday",
    "expected industrial action",
    "failure of the electricity supply earlier on this trains journey",
    "failure of the electricity supply earlier today",
    "failure of the electricity supply",
    "flood water making the railway potentially unsafe earlier today",
    "flood water making the railway potentially unsafe",
    "flooding earlier in this trains journey",
    "flooding earlier today",
    "flooding",
    "horses on the railway earlier today",
    "horses on the railway",
    "industrial action earlier today",
    "industrial action yesterday",
    "industrial action",
    "mechanical problems",
    "more trains than usual needing repairs at the same time",
    "overcrowding as this train has fewer coaches than normal",
    "overcrowding because an earlier train had fewer coaches than normal",
    "overcrowding because of a concert",
    "overcrowding because of a football match",
    "overcrowding because of a marathon",
    "overcrowding because of a rugby match",
    "overcrowding because of a sporting event",
    "overcrowding because of an earlier cancellation",
    "overcrowding because of an event",
    "overcrowding earlier on this trains journey",
    "overcrowding",
    "overhead electric line problems",
    "passengers causing a disturbance earlier on this trains journey",
    "passengers causing a disturbance on a train earlier today",
    "passengers causing a disturbance on a train",
    "passengers causing a disturbance on this train",
    "poor rail conditions",
    "predicted flooding earlier today",
    "predicted flooding",
    "sheep on the railway earlier today",
    "sheep on the railway",
    "signalling difficulties",
    "signalling staff being taken ill earlier on this trains journey",
    "signalling staff being taken ill earlier today",
    "signalling staff being taken ill",
    "slippery rails earlier in this trains journey",
    "slippery rails earlier today",
    "slippery rails",
    "staff shortages (phil)",
    "staff shortages",
    "suspected damage to a railway bridge",
    "the ambulance service dealing with an incident near the railway earlier today",
    "the ambulance service dealing with an incident near the railway yesterday",
    "the ambulance service dealing with an incident near the railway",
    "the ambulance service dealing with an incident",
    "the communication alarm being activated on a train",
    "the communication alarm being activated on this train",
    "the electricity being switched off for safety reasons earlier on this trains journey",
    "the electricity being switched off for safety reasons earlier today",
    "the electricity being switched off for safety reasons",
    "the emergency services dealing with an incident earlier today",
    "the emergency services dealing with an incident near the railway earlier today",
    "the emergency services dealing with an incident near the railway yesterday",
    "the emergency services dealing with an incident near the railway",
    "the emergency services dealing with an incident",
    "the fire alarm sounding at a station earlier today",
    "the fire alarm sounding at a station",
    "the fire alarm sounding in a signal box earlier on this trains journey",
    "the fire alarm sounding in a signal box earlier today",
    "the fire alarm sounding in a signal box",
    "the fire alarm sounding in the signalling centre earlier on this trains journey",
    "the fire alarm sounding in the signalling centre earlier today",
    "the fire alarm sounding in the signalling centre",
    "the fire brigade dealing with an incident near the railway earlier today",
    "the fire brigade dealing with an incident near the railway yesterday",
    "the fire brigade dealing with an incident near the railway",
    "the fire brigade dealing with an incident",
    "the late arrival of an incoming train",
    "the police dealing with an incident near the railway earlier today",
    "the police dealing with an incident near the railway yesterday",
    "the police dealing with an incident near the railway",
    "the police dealing with an incident",
    "the sea flooding the railway earlier today",
    "the sea flooding the railway",
    "the train conductor being taken ill",
    "the train departing late to maintain customer connections",
    "the train driver being taken ill",
    "the train for this service having broken down",
    "the train guard being taken ill",
    "the train making extra stops because a train was cancelled",
    "the train making extra stops because of service disruption",
    "the train manager being taken ill",
    "theft of overhead line electrification equipment earlier today",
    "theft of overhead line electrification equipment yesterday",
    "theft of overhead line electrification equipment",
    "theft of railway equipment earlier today",
    "theft of railway equipment yesterday",
    "theft of railway equipment",
    "theft of signalling cables earlier today",
    "theft of signalling cables yesterday",
    "theft of signalling cables",
    "theft of third rail electrical equipment earlier today",
    "theft of third rail electrical equipment yesterday",
    "theft of third rail electrical equipment",
    "this train being late from the depot",
    "this train breaking down",
    "this train hitting an obstruction on the line earlier in its journey",
    "this train hitting an obstruction on the line earlier on this trains journey",
    "this train hitting an obstruction on the line earlier today",
    "this train hitting an obstruction on the line",
    "this train not stopping at a station it was supposed to earlier in its journey",
    "this train not stopping at a station it was supposed to earlier today",
    "this train not stopping at a station it was supposed to",
    "this train not stopping in the correct position at a station earlier in its journey",
    "this train not stopping in the correct position at a station earlier today",
    "this train not stopping in the correct position at a station",
    "this trains automatic braking system being activated earlier in its journey",
    "this trains automatic braking system being activated earlier today",
    "this trains automatic braking system being activated",
    "train crew being delayed by service disruption",
    "train crew being delayed",
    "trains being involved in an accident",
    "trespass on the line",
    "trespassers on the railway earlier in this trains journey",
    "trespassers on the railway earlier today",
    "trespassers on the railway",
    "urgent repairs to a bridge earlier today",
    "urgent repairs to a bridge",
    "urgent repairs to a tunnel earlier today",
    "urgent repairs to a tunnel",
    "urgent repairs to the railway earlier today",
    "urgent repairs to the railway",
    "urgent repairs to the track earlier today",
    "urgent repairs to the track",
    "vandalism at a station earlier today",
    "vandalism at a station yesterday",
    "vandalism at a station",
    "vandalism of railway equipment earlier today",
    "vandalism of railway equipment yesterday",
    "vandalism of railway equipment",
    "vandalism on a train earlier today",
    "vandalism on a train yesterday",
    "vandalism on a train",
    "vandalism on this train earlier today",
    "vandalism on this train yesterday",
    "vandalism on this train",
    "vandalism",
    "waiting for a part of the train to be attached",
]

r_map = {}

suffixes = [
    "earlier",
    "earlier in this trains journey",
    "earlier in its journey",
    "earlier on this trains journey",
    "earlier today",
    "yesterday",
]

for r in reasons:
    for s in suffixes:
        if r.endswith(s):
            unsuffixed = r[: -len(s)].strip()

            if unsuffixed not in r_map:
                r_map[unsuffixed] = []

            r_map[unsuffixed].append(s)

            break
    else:
        if r not in r_map:
            r_map[r] = [""]
        else:
            r_map[r].append("")


jsons = json.dumps(r_map, indent=4)

print(jsons)
